
version: '3.8' 

services:
  ilumeo-frontend:
    image: ilumeo-frontend:latest
    build:
      dockerfile: Dockerfile
      context: .
    container_name: ilumeo-frontend 
    restart: always
    ports:
      - ${PROJECT_PORT}:80
    volumes:
      - "./logs:/var/log/nginx"
    env_file:
      - .env
